
# spring:
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: PostgreSQL9Dialect
#        jdbc.batch_size: 20
#        format_sql: true
#        generate_statistics: true
#        cache:
#          use_query_cache: false
#          use_second_level_cache: false
#          use_structured_entries: false
#          use_minimal_puts: false
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/mywp_1
#    username: postgres
#    password: Rain@11
#    driverClassName: org.postgresql.Driver